apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-helmrepository
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://dl.gitea.io/charts/'
    chart: 'gitea'
    targetRevision: '10.0.0'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true