apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  releaseName: gitea
  chart:
    spec:
      chart: gitea
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
  interval: 5m
  valuesFilePath: gitea-values.yaml