apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.18.3  # Correct image reference
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"